naminhaestante_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('resenhas/', include('resenhas.urls')),
    path('admin/', admin.site.urls),
]

resenhas/urls.py
from django.urls import path

from . import views

app_name = 'resenhas'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('create', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment', views.create_comment, name='comment'),
    path('categories', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:category_id>', views.detail_category, name='category-detail'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('recomendacoes/', views.recomendacoes, name='recomendacoes'),
]

resenhas/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255, verbose_name="Título")
    author = models.CharField(max_length=255, verbose_name="Autor")
    publish_year = models.IntegerField(verbose_name="Ano de Publicação")
    cover_url = models.URLField(max_length=200, null=True, verbose_name="URL da Capa")
    
    content = models.CharField(max_length=10000, verbose_name="Conteúdo")
    review_score = models.IntegerField(verbose_name="Avaliação")
    post_date = models.DateTimeField(verbose_name="Data de Postagem")

    def __str__(self):
        return f"{self.name}, de {self.author}"

class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Autor"
    )
    text = models.CharField(max_length=255, verbose_name="Texto")
    post_date = models.DateTimeField(verbose_name="Data de Postagem")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Resenha")

    def __str__(self):
        return f'"{self.text}", {self.author}'

class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="Nome")
    description = models.CharField(max_length=255, verbose_name="Descrição")
    posts = models.ManyToManyField(Post, verbose_name="Resenhas")

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

resenhas/forms.py
from django import forms

from .models import Comment


class PostForm(forms.Form):
    name = forms.CharField(label='Nome', max_length=255)
    author = forms.CharField(label='Autor', max_length=255)
    publish_year = forms.IntegerField(label='Ano de Publicação')
    cover_url = forms.URLField(label='URL da Capa', max_length=200)

    review_score = forms.IntegerField(label="Avaliação (1-5)", min_value=1, max_value=5)
    content = forms.CharField(label="Conteúdo (em HTML)", max_length=10000)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

resenhas/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, render
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.views import generic

from .models import Category, Comment, Post
from .forms import CommentForm


class PostListView(generic.ListView):
    model = Post
    template_name = 'resenhas/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'resenhas/detail.html'

class PostCreateView(generic.CreateView):
    model = Post
    template_name = 'resenhas/create.html'
    fields = [
        'name',
        'author',
        'publish_year',
        'cover_url',
        'review_score',
        'post_date',
        'content',
    ]

    def get_success_url(self):
        return reverse('resenhas:detail', kwargs={'pk': self.object.pk})

class PostUpdateView(generic.UpdateView):
    model = Post
    template_name = 'resenhas/update.html'
    fields = [
        'name',
        'author',
        'publish_year',
        'cover_url',
        'review_score',
        'post_date',
        'content',
    ]
    
    def get_success_url(self):
        return reverse('resenhas:detail', kwargs={'pk': self.object.pk})

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'resenhas/delete.html'
    success_url = reverse_lazy('resenhas:index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            text = form.cleaned_data['text']
            post_date = datetime.now()
            comment = Comment(
                author=author,
                text=text,
                post_date=post_date,
                post=post
            )
            comment.save()
            return HttpResponseRedirect(reverse('resenhas:detail', args=(post_id,)))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'resenhas/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'resenhas/categories.html'

def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category, 'post_list': category.posts.all()}
    return render(request, 'resenhas/index.html', context)

staticpages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'staticpages/index.html', {})

def about(request):
    return render(request, 'staticpages/about.html', {})

def recomendacoes(request):
    return render(request, 'staticpages/recomendacoes.html', {})

resenhas/templates/resenhas/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}

<h2>Categorias</h2>

{% if category_list %}
<ul>
    {% for category in category_list %}
          <li><a href="{% url 'resenhas:category-detail' category.id %}">{{ category.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>Não foi encontrada nenhuma categoria</p>
{% endif %}
{% endblock content %}

resenhas/templates/resenhas/comment.html
{% extends 'base.html' %}

{% block title %}
Fazer comentário
{% endblock title %}

{% block content %}
<h2>Fazer comentário na resenha de {{ post.name }}</h2>
<form method="POST" action="{% url 'resenhas:comment' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publicar</button>
    <a href="{% url 'resenhas:detail' post.id %}">Voltar</a>
</form>
{% endblock content %}

resenhas/templates/resenhas/create.html
{% extends 'base.html' %}

{% block title %}
Criar resenha
{% endblock title %}

{% block content %}
<h2>Criar nova resenha</h2>
<form method="POST" action="{% url 'resenhas:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
    <a href="{% url 'resenhas:index' %}">Cancelar</a>
</form>
{% endblock content %}

resenhas/templates/resenhas/delete.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<form action="{% url 'resenhas:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a resenha do livro "{{ post.name }} ({{ post.publish_year }})"?
    </p>
    <button type="submit">Apagar</button>
    <a href="{% url 'resenhas:detail' post.id %}">Cancelar</a>
</form>

{% endblock content %}

resenhas/templates/resenhas/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }}
{% endblock title %}

{% block content %}
<a href="{% url 'resenhas:index' %}">Voltar</a><br>
<header class="header-resenha">
    <img src="{{ post.cover_url }}" alt="capa">
    <div class="info-resenha">
        <h2>{{ post.name }}</h2>
        <ul>
            <li>Autor: {{ post.author }}</li>
            <li>Ano de publicação: {{ post.publish_year }}</li>
            <br>
            <li>Avaliação: {{ post.review_score }}/5</li>
            <li>Data da resenha: {{ post.post_date|date }}</li>
            <br>
            {% if post.category_set.all %}
                <li>
                    Categorias:
                    <ol>
                        {% for category in post.category_set.all %}
                            <li><a href="{% url 'resenhas:category-detail' category.id %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ol>
                </li>
            {% endif %}
            <br>
            <li><a href="{% url 'resenhas:update' post.id %}">Editar resenha</a></li>
            <li><a href="{% url 'resenhas:delete' post.id %}">Apagar resenha</a></li>
        </ul>
    </div>
</header>
    
{{ post.content|safe }}

<br>
<h3>Comentários</h3>
<ul>
    {% if post.comment_set.all %}
        {% for comment in post.comment_set.all|dictsortreversed:'post_date' %}
            <figure>
                <blockquote>
                    "{{ comment.text }}"
                </blockquote>
                <figcaption>- {{ comment.author }}, {{ comment.post_date|date }}</figcaption>
            </figure>
        {% endfor %}
    {% else %}
        <p>Ainda não existe nenhum comentário para essa resenha.</p>
    {% endif %}
</ul>
<a href="{% url 'resenhas:comment' post.id %}"><button>Fazer comentário</button></a>
{% endblock content %}

resenhas/templates/resenhas/index.html
{% extends 'base.html' %}

{% block title %}
Resenhas
{% endblock title %}

{% block content %}

{% if category %}
    <h2>{{ category.name }}</h2>

    <p>{{ category.description }}</p>
    
    <h3>Resenhas nessa categoria</h3>
{% else %}
    <h2>Resenhas</h2>
    <a href="{% url 'resenhas:create' %}">Criar resenha</a>
{% endif %}

{% if post_list %}
<div class="lista-livros">
    {% for post in post_list %}
        <a class="card-livro" href="{% url 'resenhas:detail' post.id %}">
            <img class="capa-card" src="{{ post.cover_url }}" alt="capa"><br>
            <p>{{ post.name }} ({{ post.publish_year }})</p>
        </a>    
    {% endfor %}
</div>
{% else %}
<p>Não foi encontrada nenhuma resenha</p>
{% endif %}
{% endblock content %}

resenhas/templates/resenhas/update.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h2>Atualizar resenha</h2>
<form method="POST" action="{% url 'resenhas:update' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
    <a href="{% url 'resenhas:detail' post.id %}">Cancelar</a>
</form>
{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre o Autor
{% endblock title %}

{% block content %}
<h2>Sobre o Autor</h2>

<p>
    Henrique Barros Oliveira, autor do Na Minha Estante, é um ávido leitor desde a infância. 
    Nascido em Salvador, Bahia, ele logo se apaixonou com o mundo da fantasia e da ficção científica 
    com sagas como "Harry Potter", "Percy Jackson e os Olimpianos" e "As Crônicas de Nárnia".
</p>
<p>
    Atualmente, Henrique mora <del>morava</del> em São Paulo, pois cursa Engenharia Mecatrônica na Poli-USP. 
    Ele faz parte do grupo de pessoas que esperam eternamente os últimos livros de "As Crônicas de Gelo e Fogo", 
    de George R. R. Martin e de "A Crônica do Matador do Rei", de Patrick Rothfuss.
</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<p>Bem vindo ao Na Minha Estante!</p>
<p>Neste site, você encontrará resenhas e recomendações de livros.</p>
{% endblock content %}

staticpages/templates/staticpages/recomendacoes.html
{% extends 'base.html' %}

{% block title %}
Recomendações
{% endblock title %}

{% block content %}
<h2>Recomendações</h2>

<p>
    Se você leu algumas de minhas resenhas, deve ter percebido que eu sou obcecado com grandes séries 
    de fantasia e ficção. Quanto mais épico, quanto mais complexo o mundo, sua política e sua mágica, 
    melhor. Sendo assim, eu queria recomendar aqui algumas das minhas sagas favoritas, e quais são 
    melhores para se começar no incrível mundo da fantasia.
</p>
<p>
    Eu costumo dividir as séries de ficção que eu leio em duas categorias. A primeira consiste nos livros 
    em que a magia e a ficção são construidas em cima do mundo real, seja pela adição de seres e realidades 
    no mundo presente, seja mostrando um mundo no futuro. Algumas das séries que eu mais gosto são:
</p>
<ul>
    <li>Harry Potter</li>
    <li>Os Instrumentos Mortais</li>
    <li>Jogos Vorazes</li>
</ul>
<p>
    A outra categoria consiste nos livros que criam um universo completamente diferente do nosso, embora 
    inspirações e metáforas possam ser percebidas. Normalmente esses livros são um pouco mais complexos 
    de ler, pois os autores amam nos jogar no meio de um contexto com poucas explicações no começo. 
    Atualmente, esses são os tipos de série que eu tenho gostado mais. Os autores conseguem controlar 
    todos os aspectos do universo, desde a política até a ecologia, podendo explorar cenários e histórias 
    muito diversas. Alguns favoritos meus são:
</p>
<ul>
    <li><em>The Stormlight Archives</em></li>
    <li><em>A Song of Ice and Fire</em></li>
    <li><em>The Kingkiller Chronicles</em></li>
    <li><em>Mistborn</em></li>
</ul>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} | Na Minha Estante</title>
        <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="icon" href="{% static 'Hopstarter-Soft-Scraps-Book.ico' %}">
    </head>
<body>
    <header id="header-principal">
        <!-- https://unsplash.com/photos/NIJuEQw0RKg -->
        <img class="img-estante" src="https://images.unsplash.com/photo-1521587760476-6c12a4b040da?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80" alt="estante">
        <div id="titulo-nav">
            <h1><a href="{% url 'index' %}">Na Minha Estante</a></h1>
            <nav>
                <ul>
                    <!-- TODO -->
                    <li><a href="{% url 'resenhas:index' %}">Resenhas</a></li> 
                    <li><a href="{% url 'resenhas:categories' %}">Categorias</a></li>
                    <li><a href="{% url 'recomendacoes' %}">Recomendações</a></li>
                    <li><a href="{% url 'about' %}">Sobre o Autor</a></li>
                </ul>
            </nav>
        </div>
        <img class="img-estante" src="https://images.unsplash.com/photo-1521587760476-6c12a4b040da?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80" alt="estante">
    </header>

    <main>
        <section>
            {% block content %}
            {% endblock content %}
        </section>
    </main>

    <footer>
        <p>Copyright 2021 Henrique Barros</p>
    </footer>
</body>
</html>